CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_DYNAMIC_INTERRUPTS=y

CONFIG_ADC=y

CONFIG_SENSOR=y


# --- CONFIGURAÇÕES DE LOGGING ---

# Ativa o subsistema de log
CONFIG_LOG=y

# Define o backend padrão para enviar os logs via UART (cabo USB para o PC)
CONFIG_LOG_BACKEND_UART=y

# Ativa cores no terminal para diferenciar visualmente INFO, WARN, ERR
CONFIG_LOG_BACKEND_SHOW_COLOR=y

# Adiciona o carimbo de tempo (timestamp) em milissegundos a cada linha
CONFIG_LOG_BACKEND_FORMAT_TIMESTAMP=y

# (Opcional) Define o modo diferido. Os logs não travam o processamento
CONFIG_LOG_MODE_DEFERRED=y